#define SAMPLING_FREQ 44100.0f
#define ADSR_MAX_TIME SAMPLING_FREQ * 2
#define FILTER_TYPE_LPF 0
#define FILTER_TYPE_HPF 1
#define FILTER_TYPE_BPF 2
#define FILTER_TYPE_PEAKINGEQ 3
#define FILTER_TYPE_LOWSHELF 4
#define FILTER_TYPE_HIGHSHELF 5